package azure

const TerraformAzureAPIMxCOMMON = `# Generated by Aldev, do not edit!

# --------------------------------------------------------------------------- #
# --- APIM integration for the {{.AppName}} API
# ---
# --- This file is meant to be re-applied by CI/CD whenever the API doc
# --- (eg data/api-doc.yaml) changes, 
# --- so that APIM always reflects the current API contract.
# --------------------------------------------------------------------------- #

# --------------------------------------------------------------------------- #
# --- Input variables
# --------------------------------------------------------------------------- #

variable "config" {
  type = object({
    env                  = string # The current env: dev, qua, or prd, for instance
    environment_sub_name = string # The name of the subscription hosting all the resources needed for this particular environment
    apim_sub_name        = string # The name of the subscription hosting resources related to tools & supervision
    apim_name            = string # The name of the API manager we use
    apim_rg              = string # The resource group the API manager belongs to
    domain_name          = string # The full domain name, something like: companyname.com
  })
}

# --------------------------------------------------------------------------- #
# --- Subscriptions
# --------------------------------------------------------------------------- #

provider "azurerm" {
  features {}
  alias = "global"
}

data "azurerm_subscriptions" "all" {
  provider = azurerm.global
}

locals {
  apim_subscription = one([
    for s in data.azurerm_subscriptions.all.subscriptions
    : s if s.display_name == var.config.apim_sub_name
  ])
  environment_subscription = one([
    for s in data.azurerm_subscriptions.all.subscriptions
    : s if s.display_name == var.config.environment_sub_name
  ])
}

provider "azurerm" {
  features {}
  alias           = "apim_sub"
  subscription_id = local.apim_subscription.subscription_id
}

provider "azurerm" {
  features {}
  alias           = "environment_sub"
  subscription_id = local.environment_subscription.subscription_id
}

# --------------------------------------------------------------------------- #
# --- Data sources
# --------------------------------------------------------------------------- #

# The APIM instance (lives in the APIM subscription)
data "azurerm_api_management" "apim" {
  provider            = azurerm.apim_sub
  name                = var.config.apim_name
  resource_group_name = var.config.apim_rg
}

# The ACA container app for current environment (lives in the current env sub)
data "azurerm_container_app" "aca" {
  provider            = azurerm.environment_sub
  name                = "aca-{resource_ns}-${var.config.env}-{{.AppNameLower}}"
  resource_group_name = "rg-{resource_ns}-${var.config.env}-{{.AppNameLower}}"
}

# --------------------------------------------------------------------------- #
# --- APIM Backend → points to the ACA app ingress
# --------------------------------------------------------------------------- #

resource "azurerm_api_management_backend" "backend" {
  provider            = azurerm.apim_sub
  name                = "backend-{{.AppNameLower}}-${var.config.env}"
  resource_group_name = var.config.apim_rg
  api_management_name = data.azurerm_api_management.apim.name
  protocol            = "http"
  url                 = "https://${data.azurerm_container_app.aca.ingress[0].fqdn}"
}

# --------------------------------------------------------------------------- #
# --- APIM API → imported from the OpenAPI spec
# ---
# --- Re-running 'terraform apply' after a spec change will push the updated
# --- contract to APIM automatically (CI/CD trigger point).
# --------------------------------------------------------------------------- #

resource "azurerm_api_management_api" "api" {
  provider              = azurerm.apim_sub
  name                  = "{{.AppNameLower}}-${var.config.env}"
  resource_group_name   = var.config.apim_rg
  api_management_name   = data.azurerm_api_management.apim.name
  revision              = "1"
  display_name          = "{{.AppName}} (${var.config.env})"
  path                  = "{{.AppNameLower}}-${var.config.env}"
  protocols             = ["https"]
  subscription_required = false
  description           = "{{.AppDesc}}"

  # Loaded from the project's API doc: any change to that file will be
  # detected by Terraform and pushed to APIM on the next apply.
  import {
    content_format = "openapi"
    content_value  = replace(file("../../../../{{.API.Doc.Path}}"), "title: {{.AppName}}", "title: {{.AppName}} (${var.config.env})")
  }
}

# --------------------------------------------------------------------------- #
# --- APIM API Policy → routes every call to the ACA backend
# --------------------------------------------------------------------------- #

resource "azurerm_api_management_api_policy" "api_policy" {
  provider            = azurerm.apim_sub
  api_name            = azurerm_api_management_api.api.name
  api_management_name = data.azurerm_api_management.apim.name
  resource_group_name = var.config.apim_rg

  xml_content = <<-XML
    <policies>
      <inbound>
        <base />
        <set-backend-service backend-id="${azurerm_api_management_backend.backend.name}" />
        <authentication-managed-identity resource="api://${var.config.domain_name}/app-{resource_ns}-{{.AppNameLower}}" />
      </inbound>
      <backend><base /></backend>
      <outbound><base /></outbound>
      <on-error><base /></on-error>
    </policies>
  XML
}
`
