package azure

const TerraformAzureAPIMxENV = `# Generated by Aldev, do not edit!

# --------------------------------------------------------------------------- #
# --- Main Terraform config to update the APIM configuration for the %[1]s env
# --------------------------------------------------------------------------- #
locals {
  config = {
    # The current env: dev, qua, or prd, for instance
    env = "%[1]s"
    # The name of the subscription hosting all the resources needed for this particular environment
    environment_sub_name = "{environment_sub_name}"
    # The name of the subscription hosting the APIM instance
    apim_sub_name = "{apim_sub_name}"
    # The name of the API manager we use
    apim_name = "{apim_name}"
    # The resource group the API manager belongs to
    apim_rg = "{apim_rg}"
    # The full domain name
    domain_name = "{domain_name}"
  }
}

module "apim_%[1]s" {
  source = "../"
  config = local.config
}

`
