package utils

import (
	"fmt"

	core "github.com/aldesgroup/corego"
	"gopkg.in/yaml.v3"
)

// ----------------------------------------------------------------------------
// Generating API config files
// ----------------------------------------------------------------------------

func generateAPIConfFile(envName string, envConfig *APIRuntimeConfig, regen bool, returnResolvedConfig bool) map[string]interface{} {
	// checking the existing config file
	confFileName := fmt.Sprintf("%s/conf-%s.yaml", Config().API.Build.SrcDir, envName)
	if core.FileExists(confFileName) && !regen {
		Debug("%s already exists!", confFileName)
		return *core.ReadFileFromYAML(confFileName, &map[string]interface{}{}, true)
	}

	// building the base config for the current environment
	base := mergeYAMLNodes(&Config().API.Runtimes.Common.Base, &envConfig.Base)
	base = prependValue("version", "_$_VERSION_$_", base)
	base = prependValue("port", getEnvPortString(envConfig), base)
	base = prependValue("appdesc", Config().AppDesc, base)
	base = prependValue("appname", Config().AppName, base)

	// making a new config by merging the env config on top of the common config
	newConf := &struct {
		Base   yaml.Node
		Custom yaml.Node
	}{
		Base:   *base,
		Custom: *mergeYAMLNodes(&Config().API.Runtimes.Common.Custom, &envConfig.Custom),
	}

	// marshalling
	newConfBytes, errMarsh := yaml.Marshal(newConf)
	core.PanicMsgIfErr(errMarsh, "Could not marshal merged config for env '%s'", envName)

	// writing out the file
	core.WriteStringToFile(confFileName, "# Generated by Aldev, do not edit!\n%s", string(newConfBytes))
	Debug("Just wrote file : %s", confFileName)

	// not really returning stuff
	if !returnResolvedConfig {
		return nil
	}

	// returning the resolved - i.e. merged - config as a map[string]interface{} for further use
	var resolvedConfig map[string]interface{}
	errUnmarsh := yaml.Unmarshal(newConfBytes, &resolvedConfig)
	core.PanicMsgIfErr(errUnmarsh, "Could not unmarshal merged config for env '%s'", envName)

	return resolvedConfig
}
