package templates

const DockerLocalAPI = `# Generated by aldev, do not edit!
FROM alpine:latest
RUN apk update && apk add --no-cache bash
WORKDIR /api
COPY ./{{.ResolvedBinDir}} .
COPY ./{{.API.DataDir}} data
ENTRYPOINT ./{{.AppName}}-api-local`
