package templates

const DockerLocalWEB = `# Generated by aldev, do not edit!
FROM node:alpine
WORKDIR /web
COPY {{.Web.SrcDir}}/package*.json {{.Web.SrcDir}}/.npmrc ./
RUN npm install --force
COPY {{.Web.SrcDir}}/ ./
CMD ["npm", "run", "dev"]`
