package templates

const I18NFiles = `// Generated by Aldev, do not edit!
import {initI18n} from '~/vendor/goaldn';

const translationResources = {
%s
};

// Initializes i18n with these resources
initI18n(translationResources);`
