package templates

const LocalCOMPOSE = `# Generated by Aldev, do not edit!

services:
%[1]s
    # Defines the backend Go application service
    {{.AppNameShort}}_api:
        # Uses a lightweight, glibc-compatible base to ensure host-compiled Go binaries run smoothly
        image: {{.API.Build.RunImage}}

        # Sets the starting directory inside the container for any relative paths in your code
        working_dir: /api

        volumes:
            # Mounts the host's bin folder to the container.
            # The ':z' tells Podman to relabel the files for SELinux (essential on Fedora/RHEL)
            - ../../{{.ResolvedBinDir}}:/api/bin:z
            - ../../{{.API.Build.SrcDir}}:/api/src:z
            - ../../{{.API.Build.DataDir}}:/api/data:z
            - ../../tmp:/api/tmp:z
            - ../../VERSION:/api/VERSION:ro,z

        # Executes the binary with a dynamically generated config file that includes the app version
        command:
            - sh
            - -c
            - |%[2]s
                cp src/conf-local.yaml tmp/conf-local.yaml
                APP_VERSION="$$(cat /api/VERSION)+"
                sed -i "s|_\$$_VERSION_\$$_|$${APP_VERSION}|g" tmp/conf-local.yaml
                exec ./bin/{{.AppNameKebab}}-api -config tmp/conf-local.yaml
%[3]s
        # This allows several services to talk to each other locally
        networks:
            - shared-net

    # Defines the Load Balancer
    {{.AppNameShort}}_api_lb:
        image: {{.API.LocalDev.LbImage}}

        ports:
            # Maps your laptop's port 8080 to the Nginx port 8080
            - "{{.LocalPort}}:8080"

        volumes:
            # Mounts your custom load-balancing config as Read-Only (:ro)
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

        depends_on:
            # Ensures the 'go_api' containers are created before Nginx starts looking for them
            - {{.AppNameShort}}_api

        networks:
            # The load balancer should be on this network to
            - shared-net
%[4]s
networks:
    shared-net:
        external: true
`
